name: build and deploy on pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v3

      - uses: kenchan0130/actions-system-info@master
        id: system-info

      - id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-node-modules-${{ hashFiles('package-lock.json') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - env:
          VITE_AMPLITUDE_API_KEY: ${{ secrets.VITE_AMPLITUDE_API_KEY }}
        run: npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist/

  deploy-gh-pages:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
